/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exo3 */

#ifndef _Included_exo3
#define _Included_exo3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exo3
 * Method:    fork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_exo3_fork
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
