/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class exo4 */

#ifndef _Included_exo4
#define _Included_exo4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     exo4
 * Method:    myFork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_exo4_myFork
  (JNIEnv *, jclass);

/*
 * Class:     exo4
 * Method:    myWait
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_exo4_myWait
  (JNIEnv *, jclass);

/*
 * Class:     exo4
 * Method:    myExit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_exo4_myExit
  (JNIEnv *, jclass, jint);

/*
 * Class:     exo4
 * Method:    mySleep
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_exo4_mySleep
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
